### ISSUE TITLE
Add releases for darwin and linux

### ISSUE THREAD

**Issue by KeisukeYamashita** [solo-io/autopilot#11]
## What

* Add releases
   * One way is using [goreleaser](https://github.com/goreleaser/goreleaser)

## Why

Although, there are install script `install_cli.sh`, it doesn't work because there are no releases yet.

```
filename="ap-${OS}-amd64"
url="https://github.com/solo-io/autopilot/releases/download/${AP_VERSION}/${filename}"
```

**Comment by ilackarms** [comment]
Sorry, this issue was caused by the indentation problem you fixed. Thank you @KeisukeYamashita !

Just to be transparent, Autopilot is still in an alpha stage and a refactor is in the process with a set of new features (including `multicluster` support) here: https://github.com/solo-io/autopilot/tree/rearch

**Comment by ilackarms** [comment]
Closing for now, please reopen if the issue persists

**Comment by KeisukeYamashita** [comment]
Thank you!
